"""Assemble generated images into a persistent parameter comparison grid."""

import json
import os
import hashlib
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from ..tools_registry import tool, ToolParameter

from config import get_settings
from config_version import get_config_version_manager
from core.logging import get_logger
from core.profile_context import get_current_profile
from database import MediaItem
from generation_metadata import dump_generation_metadata
from utils.lineage import record_lineage, propagate_tool_lineage
from utils.websocket import ws_manager

log = get_logger(__name__)


def _slugify(text: str) -> str:
    import re
    text = text.lower()
    text = re.sub(r'[\s_]+', '-', text)
    text = re.sub(r'[^a-z0-9-]', '', text)
    text = re.sub(r'-+', '-', text)
    text = text.strip('-')
    return text[:50] if text else 'grid'


@tool(
    name="create_parameter_sweep",
    description=(
        "Assemble a labeled comparison grid (.stimmagrid.json) from a parameter sweep — "
        "images generated by systematically varying two or more axes (e.g. LoRA strength × prompt, "
        "model × seed), with meaningful row AND column headers naming the swept parameters. "
        "Cell images remain exact embedded Media unless they already have Asset identity. "
        "This is a deliberate comparison artifact the user explicitly "
        "asks for ('grid', 'sweep', 'compare X across Y'); the parameter-grid skill owns the "
        "workflow and confirms the sweep axes with the user before generating, so invoke that "
        "skill first and let it drive. To present several ordinary results instead, use show()."
    ),
    parameters=[
        ToolParameter(
            name="media_ids",
            type="array",
            description="Media IDs in row-major order (left-to-right, top-to-bottom). Length must equal rows * cols.",
            items={"type": "integer"},
        ),
        ToolParameter(
            name="rows",
            type="integer",
            description="Number of rows in the grid",
        ),
        ToolParameter(
            name="cols",
            type="integer",
            description="Number of columns in the grid",
        ),
        ToolParameter(
            name="row_headers",
            type="array",
            description="Short labels for each row (e.g. 'elderly Japanese woman', NOT full prompts). Length must equal rows.",
            items={"type": "string"},
        ),
        ToolParameter(
            name="col_headers",
            type="array",
            description="Short labels for each column (e.g. '2000 steps', 'weight 0.8'). Length must equal cols.",
            items={"type": "string"},
        ),
        ToolParameter(
            name="title",
            type="string",
            description="Title for the grid",
        ),
        ToolParameter(
            name="description",
            type="string",
            description="Optional description of what the grid compares",
            required=False,
        ),
    ],
)
async def create_parameter_sweep(
    media_ids: List,
    rows: int,
    cols: int,
    row_headers: List[str],
    col_headers: List[str],
    title: str,
    description: str = "",
    **kwargs,
) -> str:
    session: AsyncSession = kwargs.get("session")
    if not session:
        return "Error: No database session available"

    # Normalize media_ids
    normalized_ids = []
    for item in media_ids:
        if isinstance(item, dict) and "media_id" in item:
            normalized_ids.append(item["media_id"])
        elif isinstance(item, (int, str)):
            normalized_ids.append(int(item))
        else:
            normalized_ids.append(item)
    media_ids = normalized_ids

    # Validate dimensions
    expected_count = rows * cols
    if len(media_ids) != expected_count:
        return f"Error: Expected {expected_count} media_ids ({rows}x{cols}), got {len(media_ids)}"
    if len(row_headers) != rows:
        return f"Error: Expected {rows} row_headers, got {len(row_headers)}"
    if len(col_headers) != cols:
        return f"Error: Expected {cols} col_headers, got {len(col_headers)}"

    log.info(f"[create_parameter_sweep_v2] Assembling {rows}x{cols} grid '{title}' from {len(media_ids)} media items")

    # Query all MediaItem records
    result = await session.execute(
        select(MediaItem).where(MediaItem.id.in_(media_ids))
    )
    media_items_by_id = {m.id: m for m in result.scalars().all()}

    missing = [mid for mid in media_ids if mid not in media_items_by_id]
    if missing:
        return f"Error: Media items not found: {missing}"

    # Build grid directory
    settings = get_settings()
    profile_id = get_current_profile()
    base_folder = settings.get_generation_folder_for_profile(profile_id)
    now = datetime.now()
    grid_slug = _slugify(title)
    grid_dir = Path(base_folder.path) / "grids" / str(now.year) / f"{now.month:02d}" / f"{grid_slug}-{uuid.uuid4().hex[:8]}"
    grid_dir.mkdir(parents=True, exist_ok=True)

    # Build grid JSON
    grid_content = {
        "type": "grid",
        "version": 1,
        "title": title,
        "description": description,
        "rows": rows,
        "cols": cols,
        "row_headers": list(row_headers),
        "col_headers": list(col_headers),
        "cells": [],
    }

    for idx, mid in enumerate(media_ids):
        row_idx = idx // cols
        col_idx = idx % cols
        cell_data = {"row": row_idx, "col": col_idx}
        media_item = media_items_by_id.get(mid)
        if media_item:
            media_path = Path(media_item.file_path)
            try:
                cell_data["path"] = os.path.relpath(media_path, grid_dir)
            except ValueError:
                cell_data["path"] = str(media_path)
        grid_content["cells"].append(cell_data)

    # Write grid JSON file
    grid_file_path = grid_dir / f"{grid_slug}.stimmagrid.json"
    with open(grid_file_path, 'w', encoding='utf-8') as f:
        json.dump(grid_content, f, indent=2)

    # Compute hash
    with open(grid_file_path, 'rb') as f:
        file_hash = hashlib.sha256(f.read()).hexdigest()
    stat_info = os.stat(grid_file_path)

    # Create MediaItem for the grid
    grid_media_item = MediaItem(
        file_path=str(grid_file_path),
        file_hash=file_hash,
        file_size=stat_info.st_size,
        file_format='stimmagrid.json',
        created_date=datetime.utcfromtimestamp(stat_info.st_ctime),
        modified_date=datetime.utcfromtimestamp(stat_info.st_mtime),
        indexed_date=datetime.utcnow(),
        metadata_status='completed',
        metadata_processed_at=datetime.utcnow(),
        metadata_config_version=get_config_version_manager().get_version('metadata'),
        width=0,
        height=0,
        megapixels=0,
        raw_metadata=json.dumps(grid_content),
        generation_metadata=dump_generation_metadata(
            task_type='grid-creation',
            source='agent_v2_assemble_grid',
            source_inputs=[{'media_id': mid, 'role': 'cell'} for mid in media_ids],
            extra={'cell_count': len(media_ids)},
        ),
    )

    session.add(grid_media_item)
    await session.flush()
    from storage_service import stage_managed_media

    await stage_managed_media(
        session,
        media=grid_media_item,
        profile_id=profile_id,
        remove_source=True,
    )

    output_context_kind = kwargs.get("output_context_kind")
    output_context_id = kwargs.get("output_context_id")
    if output_context_kind and output_context_id:
        from asset_service import acquire_media_owner
        await acquire_media_owner(
            session,
            media_id=grid_media_item.id,
            root_kind=output_context_kind,
            root_id=output_context_id,
            role="result",
            idempotency_key=(
                f"flow:{output_context_id}:media:{grid_media_item.id}"
                if output_context_kind == "flow_equation"
                else f"{output_context_kind}:{output_context_id}:parameter-grid:{grid_media_item.id}"
            ),
        )

    chat_id = kwargs.get("chat_id")
    if chat_id is not None:
        from asset_service import acquire_media_owner
        await acquire_media_owner(
            session,
            media_id=grid_media_item.id,
            root_kind="chat",
            root_id=chat_id,
            role="result",
            idempotency_key=f"chat:{chat_id}:parameter-grid:{grid_media_item.id}",
        )

    # Attach to project if in project context
    project_id = kwargs.get("project_id")
    if project_id is not None:
        from project_service import attach_media_to_project
        await attach_media_to_project(session, project_id, grid_media_item.id)

    await session.commit()
    await session.refresh(grid_media_item)
    from storage_service import cleanup_staged_source

    await cleanup_staged_source(session, media_id=grid_media_item.id)

    # Record Media lineage. Final promotion normalizes membership without
    # changing the identity or visibility of any independently rooted member.
    cell_media_ids = [mid for mid in media_ids if mid in media_items_by_id]
    if cell_media_ids:
        await record_lineage(session, grid_media_item.id, cell_media_ids, "grid-creation")
        await propagate_tool_lineage(session, grid_media_item.id, cell_media_ids)

        await session.commit()

    from telemetry import get_telemetry_client
    get_telemetry_client().track("grid_created", {
        "cellCount": len(media_ids),
        "actor": "agent",
    }, category="library")

    log.info(f"[create_parameter_sweep_v2] Created grid media item {grid_media_item.id}: {grid_file_path}")

    # Broadcast media_added
    await ws_manager.broadcast('media_added', {
        'media_id': grid_media_item.id,
        'count': 1,
    })

    # Trigger rescan
    try:
        from database import ControlFlag
        from sqlalchemy.dialects.sqlite import insert
        from core.app import get_rescan_event

        stmt = insert(ControlFlag).values(
            key='rescan_requested', value='true', updated_at=datetime.utcnow()
        ).on_conflict_do_update(
            index_elements=['key'],
            set_=dict(value='true', updated_at=datetime.utcnow())
        )
        await session.execute(stmt)
        await session.commit()

        rescan_event = get_rescan_event()
        if rescan_event:
            rescan_event.set()
    except Exception as e:
        log.warning(f"[create_parameter_sweep_v2] Failed to trigger rescan: {e}")

    return (
        f"<result media_id={grid_media_item.id} />"
        f"Grid '{title}' created ({rows}x{cols}, {len(media_ids)} images). "
        f"Media ID: {grid_media_item.id}. Cell images remain independent."
    )
