"""Key art crops: one hero image cropped to every aspect ratio a campaign needs.

The focal point is a judgment call and therefore a parameter: the agent picks
it, the manifest records it, rebuild replays it.
"""

from __future__ import annotations

from PIL import Image

from packages.recipes import Build, Input, Param, png_bytes, recipe

ASPECTS = {
    "16x9": (16, 9),
    "4x3": (4, 3),
    "3x2": (3, 2),
    "1x1": (1, 1),
    "4x5": (4, 5),
    "2x3": (2, 3),
    "9x16": (9, 16),
    "21x9": (21, 9),
}


def crop_to_aspect(img: Image.Image, aw: int, ah: int, fx: float, fy: float) -> Image.Image:
    """Largest ``aw:ah`` crop of ``img`` that keeps the focal point (fx, fy in 0..1) inside, centered when possible."""
    w, h = img.size
    target = aw / ah
    if w / h > target:
        cw, ch = int(round(h * target)), h
    else:
        cw, ch = w, int(round(w / target))
    cx = fx * w
    cy = fy * h
    left = min(max(0, int(round(cx - cw / 2))), w - cw)
    top = min(max(0, int(round(cy - ch / 2))), h - ch)
    return img.crop((left, top, left + cw, top + ch))


@recipe(
    id="key-art-crops",
    version=1,
    display_name="Key art crops",
    description="Crops of one hero image to standard aspect ratios around a chosen focal point, at delivery sizes",
    inputs=[
        Input("master", kind="raster", min_size=1024, description="Hero image at delivery resolution"),
    ],
    params=[
        Param("aspects", type="multi", options=list(ASPECTS), default=["16x9", "1x1", "9x16", "4x5"],
              description="Aspect ratios to produce"),
        Param("focal_x", type="number", default=0.5, minimum=0.0, maximum=1.0,
              description="Focal point x as a fraction of width (0 = left, 1 = right)"),
        Param("focal_y", type="number", default=0.5, minimum=0.0, maximum=1.0,
              description="Focal point y as a fraction of height (0 = top, 1 = bottom)"),
        Param("max_long_side", type="integer", default=4096, minimum=256, maximum=16384,
              description="Cap on the long side of each crop; crops are never upscaled"),
        Param("format", type="choice", options=["png", "jpeg"], default="jpeg", description="Output format"),
        Param("jpeg_quality", type="integer", default=92, minimum=60, maximum=100),
        Param("naming", type="naming", fields=["slug", "aspect", "width", "height"],
              default="{slug}-{aspect}-{width}x{height}"),
    ],
)
async def build(b: Build) -> None:
    master = await b.image("master")
    fmt = b.params.format
    for aspect in b.params.aspects:
        aw, ah = ASPECTS[aspect]
        crop = crop_to_aspect(master, aw, ah, b.params.focal_x, b.params.focal_y)
        long_side = max(crop.size)
        if long_side > b.params.max_long_side:
            scale = b.params.max_long_side / long_side
            crop = crop.resize((max(1, int(crop.width * scale)), max(1, int(crop.height * scale))), Image.LANCZOS)
        name = b.name(ext=fmt if fmt == "png" else "jpg", slug=b.slug, aspect=aspect, width=crop.width, height=crop.height)
        if fmt == "png":
            data = png_bytes(crop)
        else:
            import io
            buf = io.BytesIO()
            crop.convert("RGB").save(buf, format="JPEG", quality=b.params.jpeg_quality, optimize=True)
            data = buf.getvalue()
        b.derive(f"{aspect}/{name}", data, source="master")
    b.file("README.txt", (
        "Key art crops generated by Stimma. One folder per aspect ratio; crops keep the chosen focal point\n"
        f"({b.params.focal_x:.2f}, {b.params.focal_y:.2f}) in frame and are never upscaled.\n"
    ))
